<?xml version="1.0" encoding="UTF-8"?>
<!--Created with WSDLGenerator 2.0.0 by Amadeus SAS-->
<!--  Amadeus Proprietary and Confidential Information: unauthorized use and disclosure strictly forbidden. 2015 - Amadeus s.a.s - All Rights Reserved.  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:amasec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:awsl="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:int="http://wsdl.amadeus.com/HotelContent_v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://wsdl.amadeus.com/HotelContent_v1_v4" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.amadeus.com/HotelContent_v1_v4" name="AGNAMA_HotelContent_1.0_4.0">
  <wsdl:documentation>Versions: [interface: 1.0 ; technical: 4.0]</wsdl:documentation>
  <wsp:Policy wsu:Id="MessagingPolicy">
    <wsam:Addressing wsp:Optional="true">
      <wsp:Policy>
        <wsam:AnonymousResponses />
      </wsp:Policy>
    </wsam:Addressing>
  </wsp:Policy>
  <wsp:Policy wsu:Id="AmadeusPolicy">
    <wsp:PolicyReference URI="#MessagingPolicy" />
  </wsp:Policy>
  <wsdl:import namespace="http://wsdl.amadeus.com/HotelContent_v1" location="HotelContent_1.0.wsdl" />
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="AMA/2012B/AMA_WS_Session.xsd" namespace="http://xml.amadeus.com/2010/06/Session_v3" />
      <xs:import schemaLocation="AMA_WSLink.xsd" namespace="http://wsdl.amadeus.com/2010/06/ws/Link_v1" />
      <xs:import schemaLocation="AMA/2012B/AMA_SecurityHostedUser.xsd" namespace="http://xml.amadeus.com/2010/06/Security_v1" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_3.000">
    <wsdl:part name="session" element="awsse:Session" />
  </wsdl:message>
  <wsdl:message name="TransactionFlowLink_1.0">
    <wsdl:part name="link" element="awsl:TransactionFlowLink" />
  </wsdl:message>
  <wsdl:message name="AMA_SecurityHostedUser_1.000">
    <wsdl:part name="security" element="amasec:AMA_SecurityHostedUser" />
  </wsdl:message>
  <wsdl:binding name="HotelContent_Binding" type="int:HotelContent_PT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Hotel_ContentNotifReport">
      <soap:operation soapAction="http://webservices.amadeus.com/Hotel_ContentNotifReport_1.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Hotel_DescriptiveInfo">
      <soap:operation soapAction="http://webservices.amadeus.com/OTA_HotelDescriptiveInfoRQ_07.1_1A2007A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HotelContent_Service">
    <wsdl:port binding="tns:HotelContent_Binding" name="HotelContent_Port">
      <wsp:PolicyReference URI="#AmadeusPolicy" />
      <soap:address location="https://nodeD3.test.webservices.amadeus.com/1ASIWAMAAGN" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
<!--1F8B08000000000000005D8D4D0B82401445F7FE8AB75442799A04CD6E32B0202130703DE92B86E6436626A17FDF90BB56172EF79CDB92212782B40682D4E483D033830AAB6D5E9639EEA0B366121FC03DC39AD535B4DD6D83C81093A13F5EA05D79EB6021E7A326C2051698344A920920E659C9F177C0806B31D1DBC34077E8C92D72240F271B48A55C0501076B5FD23C334879C7B378C0AF608426B68E1A6B427426E718EE21C6BF1E4AFC028A2A0198CE000000-->
